// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSongs() {
  return window['go']['main']['App']['GetSongs']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
