// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetSongs():Promise<Array<model.Song>>;

export function Greet(arg1:string):Promise<string>;
